[program:uvtp-worker-vtu]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/universal-vtu-pro/artisan queue:work redis --queue=vtu --sleep=3 --tries=1 --max-time=3600 --memory=256
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=4
redirect_stderr=true
stdout_logfile=/var/log/uvtp/worker-vtu.log
stopwaitsecs=3600

[program:uvtp-worker-notifications]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/universal-vtu-pro/artisan queue:work redis --queue=notifications --sleep=3 --tries=3 --max-time=3600 --memory=128
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/uvtp/worker-notifications.log
stopwaitsecs=3600

[program:uvtp-worker-webhooks]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/universal-vtu-pro/artisan queue:work redis --queue=webhooks --sleep=3 --tries=5 --max-time=3600 --memory=128
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/uvtp/worker-webhooks.log
stopwaitsecs=3600

[program:uvtp-worker-reports]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/universal-vtu-pro/artisan queue:work redis --queue=reports --sleep=10 --tries=1 --max-time=3600 --memory=512
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/uvtp/worker-reports.log
stopwaitsecs=3600

[program:uvtp-worker-default]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/universal-vtu-pro/artisan queue:work redis --queue=default --sleep=3 --tries=3 --max-time=3600 --memory=128
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/uvtp/worker-default.log
stopwaitsecs=3600

[group:uvtp-workers]
programs=uvtp-worker-vtu,uvtp-worker-notifications,uvtp-worker-webhooks,uvtp-worker-reports,uvtp-worker-default
